name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
      - name: Import signing certificate (optional)
        if: ${{ secrets.APPLE_CERT_P12_BASE64 }}
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_CERT_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERT_P12_PASSWORD }}
      - name: Install dependencies
        run: npm ci
      - name: Build Tauri (DMG)
        run: npm run tauri:build
      - name: Codesign app (optional)
        if: ${{ secrets.APPLE_SIGNING_IDENTITY }}
        run: |
          APP_PATH="src-tauri/target/release/bundle/macos/Blip RSVP Reader.app"
          if [ -d "$APP_PATH" ]; then
            codesign --deep --force --options runtime --sign "${{ secrets.APPLE_SIGNING_IDENTITY }}" "$APP_PATH"
          fi
      - name: Notarize and staple (optional)
        if: ${{ secrets.APPLE_ID && secrets.APPLE_TEAM_ID && secrets.APPLE_APP_PASSWORD }}
        run: |
          DMG_PATH=$(ls src-tauri/target/release/bundle/dmg/*.dmg | head -n 1)
          xcrun notarytool submit "$DMG_PATH" --apple-id "${{ secrets.APPLE_ID }}" \
            --team-id "${{ secrets.APPLE_TEAM_ID }}" --password "${{ secrets.APPLE_APP_PASSWORD }}" --wait
          xcrun stapler staple "$DMG_PATH"
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: src-tauri/target/release/bundle/dmg/*.dmg

  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
      - name: Install NSIS
        run: choco install nsis -y
      - name: Install dependencies
        run: npm ci
      - name: Build Tauri (EXE)
        run: npm run tauri:build
        env:
          CI: true
          RUSTFLAGS: -Ctarget-feature=+crt-static
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: src-tauri/target/release/bundle/nsis/*.exe

  publish-release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            dist/**/*.dmg
            dist/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


